### ISSUE TITLE
Config 

### ISSUE THREAD

**Issue by LNonymous** [XNonymous-N2/AutoSell#1]
Warum erstellst du für jede Config eine Klasse wenn du in den Einzelnen Klassen keinerlei Code ausführst? Warum erstellst du nicht 
einfach 3 Instanzen von der Config Klasse. 
Man merkt das du keinerlei Ahnung hast von dem was du eigentlich machst.

**Comment by LNonymous** [comment]
Ich meine du könntest wenn du schon eine Klasse für jede Config erstellst wenigstens den Code aus der Main Klasse in den einzelnen Config Klassen machen.

**Comment by XNonymous-N2** [comment]
Guten Morgen LNonymous,

Vielen dank für dein Feedback.
Ich bemühe mich, dass mein Code sauber aussieht.

Ich habe sehr wohl Ahnung was ich eigentlich mache.

Falls du Verbesserungsvorschläge hast, dann komm doch bitte auf meinen Discord Server. (Link auf meinem Spigot Profil)

Liebe Grüße,
XNonymous

**Comment by LNonymous** [comment]
Ich merke wie viel Ahnung du hast :)

**Comment by XNonymous-N2** [comment]
Guten Tag LNonymous,

wie ich bereits erwähnt habe, ich habe Ahnung.

Bitte höre auf in Issues zu schreiben sonst muss ich leider diesen Issue löschen.

LG XNonymous

**Comment by LNonymous** [comment]
Okay. Ich würde nur gerne wissen warum du die oben genannten Punkte so gemacht hast.
LG Lino

**Comment by XNonymous-N2** [comment]
Guten Tag LNonymous,

Ich finde mein Code ist gut.
Bei Verbesserungsvorschlägen komm gerne auf meinen Discord, danke.

LG XNonymous
